### PR TITLE
Update lib/bencodr/parser.rb

### PR DESCRIPTION
**Pull request by Tarang**
Modified file to exclude using regular expressions so large torrents can be parsed

### CODE REVIEW

**Comment by blatyo** [comment]
Can you add a file which generates the error your providing the fix for into `spec/samples`?

**Comment by Tarang** [comment]
The torrent I used wasn't of the 'good' kind. But try any torrent above about 115 kb and it'll spit the error out

**Comment by Tarang** [comment]
Lets see ill try make one

**Comment by Tarang** [comment]
Could you also merge this one sorry they ended up as seperate pulls

**Comment by blatyo** [comment]
I merged, but I'll need to do some more work on this before I can release a gem. A couple tests are failing and there needs to be additional tests for the case you brought up.

http://travis-ci.org/#!/blatyo/bencodr

**Pull request merged**
